"""The `word_read` / `word_write` command vocabularies.

One source of truth, read three ways: `server.py` publishes these as the `enum`
of each tool's `command` parameter, the dispatchers validate against them, and
the error copy turns a miss into a `did you mean` (see `.._suggest`).

They live here rather than inline in `server.py` because the schema and the
dispatcher must not drift — `tests/test_dispatch_errors.py` asserts every name
is actually handled, and that every `WRITE_ACTION_ALIASES` entry builds the op
it claims to.
"""

from __future__ import annotations

READ_COMMANDS: tuple[str, ...] = (
    "status",
    "guide",
    "outline",
    "paragraphs",
    "find",
    "read_bookmark",
    "read_cc",
    "read_section",
    "to_markdown",
    "to_html",
    "digest",
    "between",
    "nearest_heading",
    "find_paragraphs",
    "table_list",
    "table_read",
    "table_records",
    "styles",
    "comments",
    "revisions",
    "read_text",
    "track",
    "sections",
    "footnotes",
    "endnotes",
    "images",
    "read_image",
    "equations",
    "charts",
    "shapes",
    "hyperlinks",
    "fields",
    "properties",
    "watermark",
    "variables",
    "proofing",
    "lint",
    "checkpoint",
    "diff",
    "format_info",
    "list_levels",
    "location",
    "stats",
    "theme",
    "themes",
)

WRITE_COMMANDS: tuple[str, ...] = (
    "insert",
    "insert_block",
    "insert_section",
    "insert_markdown",
    "replace_section",
    "delete_paragraph",
    "append",
    "prepend",
    "replace",
    "write_bookmark",
    "write_cc",
    "apply_style",
    "format_paragraph",
    "format_run",
    "set_shading",
    "set_borders",
    "cell_valign",
    "drop_cap",
    "add_tab_stop",
    "add_style",
    "set_style",
    "list",
    "comment",
    "revision",
    "table",
    "header",
    "footer",
    "track",
    "watermark",
    "text_box",
    "insert_image",
    "insert_equation",
    "insert_chart",
    "format_chart",
    "format_axis",
    "add_trendline",
    "set_series_color",
    "format_series",
    "add_error_bars",
    "set_shape_wrap",
    "set_shape_crop",
    "set_shape_position",
    "set_shape_size",
    "format_shape",
    "set_shape_alt_text",
    "set_shape_text",
    "set_shape_rotation",
    "set_shape_z_order",
    "set_shape_text_frame",
    "replace_shape_image",
    "delete_shape",
    "group_shapes",
    "ungroup_shape",
    "set_image_alt_text",
    "set_image_size",
    "set_image_crop",
    "insert_break",
    "insert_field",
    "update_fields",
    "regularize",
    "set_property",
    "delete_property",
    "set_variable",
    "delete_variable",
    "insert_footnote",
    "insert_endnote",
    "insert_toc",
    "add_bookmark",
    "pin",
    "pin_outline",
    "add_hyperlink",
    "set_hyperlink",
    "insert_cross_reference",
    "insert_caption",
    "create_content_control",
    "set_cc_properties",
    "set_cc_items",
    "mark_index_entry",
    "insert_index",
    "insert_table_of_figures",
    "set_bibliography_style",
    "add_source",
    "insert_citation",
    "insert_bibliography",
    "mark_citation",
    "insert_table_of_authorities",
    "apply_theme",
    "set_theme_colors",
    "set_theme_fonts",
    "page_setup",
    "save",
    "save_as",
    "export_pdf",
)

# Four `word_write` commands are themselves dispatchers, keyed on `action`.
WRITE_ACTIONS: dict[str, tuple[str, ...]] = {
    "list": ("apply", "remove", "restart", "indent", "outdent", "format"),
    "comment": ("add", "resolve", "delete"),
    "revision": ("accept", "reject", "accept_all", "reject_all"),
    "table": (
        "create",
        "set_cell",
        "add_row",
        "delete_row",
        "add_column",
        "delete_column",
        "merge_cells",
        "split_cell",
        "append_record",
        "update_row",
        "set_heading_row",
        "autofit",
        "delete",
        "set_style",
        "set_alignment",
        "set_borders",
        "set_banding",
    ),
}

# The `exec` op names behind those sub-dispatchers. An agent that knows the op
# vocabulary reaches for `word_write(command="add_row")` — which is not a
# command at all — so map each op back to the `(command, action)` pair that
# performs it. This is exact, not fuzzy: no string metric could recover `table`
# from `delete_row`.
WRITE_ACTION_ALIASES: dict[str, tuple[str, str]] = {
    "apply_list": ("list", "apply"),
    "remove_list": ("list", "remove"),
    "restart_numbering": ("list", "restart"),
    "indent_list": ("list", "indent"),
    "outdent_list": ("list", "outdent"),
    "apply_list_format": ("list", "format"),
    "add_comment": ("comment", "add"),
    "resolve_comment": ("comment", "resolve"),
    "delete_comment": ("comment", "delete"),
    "accept_revision": ("revision", "accept"),
    "reject_revision": ("revision", "reject"),
    "accept_all_revisions": ("revision", "accept_all"),
    "reject_all_revisions": ("revision", "reject_all"),
    "create_table": ("table", "create"),
    "set_cell": ("table", "set_cell"),
    "add_row": ("table", "add_row"),
    "delete_row": ("table", "delete_row"),
    "add_column": ("table", "add_column"),
    "delete_column": ("table", "delete_column"),
    "merge_cells": ("table", "merge_cells"),
    "split_cell": ("table", "split_cell"),
    "append_record": ("table", "append_record"),
    "update_row": ("table", "update_row"),
    "set_heading_row": ("table", "set_heading_row"),
    "autofit_table": ("table", "autofit"),
    "delete_table": ("table", "delete"),
    "set_table_style": ("table", "set_style"),
    "set_table_alignment": ("table", "set_alignment"),
    "set_table_borders": ("table", "set_borders"),
    "set_table_banding": ("table", "set_banding"),
}
